version: '3.8'

services:
  engineDB:
    image: postgres:12
    restart: always
    container_name: engine-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB_ENGINE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - database_network
    ports:
      - "${POSTGRES_PORT_ENGINE}:5432"
    volumes:
      - engine-data:/var/lib/postgresql/data
    expose:
      - "${POSTGRES_PORT_ENGINE}"
    env_file:
      - keys.env
    deploy:
      resources:
        limits:
          memory: 220M
        reservations:
          memory: 100M
volumes:
  engine-data:

networks:
  database_network:
    external: true
