server:
  port: 9195
  servlet:
    context-path: /uol-compass/san-giorgio
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_PROVIDER}
spring:
  profiles:
    active:
      - api-doc
  application:
    name: san-giorgio
  datasource:
    url: jdbc:postgresql://localhost:5433/enginedb
    username: postgres
    password: qa.4736
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com:
      ecwid.consul: OFF
    org:
      springframework:
        cloud: OFF
        security: INFO
  charset:
    console:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

desafio:
  uol-compass:
    ambiente:
      openapi:
        dev-url: http://localhost:9195${server.servlet.context-path}
        hml-url: http://hml:9195${server.servlet.context-path}
        prd-url: http://prd:9195${server.servlet.context-path}
